### ISSUE TITLE
[BUG] Cannot find module 'ts-log-debug/lib/layouts/utils/colorizeUtils'

### ISSUE THREAD

**Issue by laolarou726** [TypedProject/tsed#748]
## Information

- **Version:** 5.40.0
- Packages: 
    @tsed/common
    @tsed/core
    @tsed/di

I set up the basic environment for the project. And I create a basic controller in the project. When trying to run this project. It told me "Cannot find module 'ts-log-debug/lib/layouts/utils/colorizeUtils'".  Also, I did not use the "$log" in the whole project.

## Detail Errors

```

Error: Cannot find module 'ts-log-debug/lib/layouts/utils/colorizeUtils'
Require stack:
- /Users/z/node_modules/@tsed/di/lib/errors/InjectionError.js
- /Users/z/node_modules/@tsed/di/lib/services/InjectorService.js
- /Users/z/cmf-backstage/node_modules/@tsed/di/lib/index.js
- /Users/z/cmf-backstage/node_modules/@tsed/common/lib/index.js
- /Users/z/cmf-backstage/src/Index.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/luolinrui/数据/Nodejs工程/cmf-backstage/node_modules/@tsed/di/src/errors/InjectionError.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)

```

## Server.ts

```

import {GlobalAcceptMimesMiddleware, ServerLoader, ServerSettings} from "@tsed/common";
import * as bodyParser from "body-parser";
import * as compress from "compression";
import * as cookieParser from "cookie-parser";
import * as methodOverride from "method-override";

const rootDir = `${__dirname}/server/`;

@ServerSettings({
    rootDir,
    acceptMimes: ["application/json"]
})
export class Server extends ServerLoader {
    /**
     * This method let you configure the express middleware required by your application to works.
     * @returns {Server}
     */
    public $beforeRoutesInit(): void | Promise<any> {
        this
            .use(GlobalAcceptMimesMiddleware)
            .use(cookieParser())
            .use(compress({}))
            .use(methodOverride())
            .use(bodyParser.json())
            .use(bodyParser.urlencoded({
                extended: true
            }));
    }
}

```

## Index.ts
```

import {ServerLoader} from "@tsed/common";
import {Server} from "./Server";
import * as consoleP from "consola";

async function Bootstrap(): Promise<void> {
    try {
        consoleP.info("Start server...");
        const server = await ServerLoader.bootstrap(Server);

        await server.listen();
        consoleP.success("Server initialized");
    } catch (er) {
        consoleP.error(er);
    }
}

Bootstrap().catch((err) => {
    consoleP.error(err);
});

```

**Comment by Romakita** [comment]
Arf. Yesterday , I updated the ts-log-debug dependencies I forgot this point. 

I fix that ASAP

**Comment by laolarou726** [comment]
Got it! Thank you so much!

**Comment by Romakita** [comment]
The release is on going (~15minutes)

See you :)

**Comment by Romakita** [comment]
fixed :)

**Comment by TakeshiDaveau** [comment]
Hi,

I work with tsed version 5.36.2, and I'm stuck with this error, without changing any of my dependencies.

I can't update my tsed version cause I'm currently fixing an error in production. I've tried to explicitly install ts-log-debug or @tsed/logger but it doesn't work.

Do you have a workaround to get rid of this error ?

Thanks in advance

**Comment by Romakita** [comment]
Try to install the version ts-log-debug 5.2

**Comment by TakeshiDaveau** [comment]
First of all, thanks for your response.

Here is what I get :
```
backend-mongo@0.0.1 /Users/tdaveau/WebstormProjects/antiseche/backend-mongo
├─┬ @tsed/common@5.36.2
│ └── ts-log-debug@5.2.1  deduped
└── ts-log-debug@5.2.1 
```

But I still get the `Error: Cannot find module 'ts-log-debug/lib/layouts/utils/colorizeUtils'` error.

**Comment by Romakita** [comment]
Ok my bad. Install the v5.1.2 and run npm dedup.
Sorry !!!

**Comment by Romakita** [comment]
Other solution: Edit @tsed/di/lib/errors/InjectionError.js and replace ts-log-debug/lib/layouts/utils/colorizeUtils  by ts-log-debug (should work with v5.3+)

**Comment by TakeshiDaveau** [comment]
Ok thanks for that, even with v5.1.2 it doesn't work well.
But I was able to deploy my production fix, so I think for the next deploy we will try to upgrade to last version of tsed.io

**Comment by NachtRitter** [comment]
@TakeshiDaveau Also you may revert changes in package-lock.json for `ts-log-debug` package and return version that doesn't require `@tsed/logger` package.

**Comment by TranBaVinhSon** [comment]
> Ok my bad. Install the v5.1.2 and run npm dedup.
> Other solution: Edit @tsed/di/lib/errors/InjectionError.js and replace ts-log-debug/lib/layouts/utils/colorizeUtils by ts-log-debug (should work with v5.3+)

@Romakita I tried with both above solutions but still got the error. 
My tsed version is 5.31.1
Here is my code:
https://github.com/TranBaVinhSon/prometheus_express/tree/master/prometheus_tsed

<img width="958" alt="Screen Shot 2020-06-13 at 18 51 16" src="https://user-images.githubusercontent.com/12994069/84565806-e4060e80-ada6-11ea-9a9e-9f069e8c10ae.png">

**Comment by Romakita** [comment]
@TranBaVinhSon The only solution for that is to upgrade your TsED packages to an higher version :/ Sorry
